name: Trigger auto deployment for self-hosted-github-action-runner

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '.github/workflows/self-hosted-workflow.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: self-hosted-dev-test

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      # Self-hosted runners do not have az cli installed 
      # - name: Install Azure cli
      #   run: |
      #     usermod -a -G sudo root
      #     sudo apt-get -yy update && sudo apt-get install -yy ca-certificates curl apt-transport-https lsb-release gnupg
      #     curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
      #     AZ_REPO=$(lsb_release -cs)
      #     echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
      #     sudo apt-get -yy update && apt-get install -yy azure-cli

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Check Azure CLI version
      #   run: |
      #     az --version

      - name: Check OS version
        run: |
          echo "Checking OS version.."
          cat /etc/os-release
     

