name: Trigger auto deployment for self-hosted-github-action-runner

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '.github/workflows/self-hosted-workflow.yml'

  # Allow manual trigger 
  # workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Check OS version
        run: |
          echo "Checking OS version.."
          cat /etc/os-release
     

